### ISSUE TITLE
Queries on some functions like wait, send

### ISSUE THREAD

**Issue by mananjadhav** [senecajs/seneca-registry#2]
Hi,

I am trying to take this repo as a reference and make a registry for consul where I came across this example in your Readme.

```
require('seneca')()
  .use('registry')
  .start()
  .wait('role:registry,cmd:set,key:color,value:red')
  .wait('role:registry,cmd:get,key:color')
  .step(function(data){
    console.log( data.value ) // == "red"
    return true;
  })
  .end()
```

What I am confused with is the start, wait, step and end methods. Seems like these methodsare a part of Seneca core? Is that so?

I was checking the senecajs.org for its documentation and API but couldn't find much information about these functions.

I am trying to build microservices system with self-registration model. Would be great if you could share some insights on these functions and how can I use them with the seneca listen/client functions.

**Comment by rjrodger** [comment]
these have been moved to plugin in Seneca 3: senecajs/seneca-chain
